version: "20.0"
services:
  api_node:
    context: .
    dockerfile: dockerfile.dev
    port:
      - "2000:2000"
    links:
      - nomgo1
    volumes:
      - .:/home/app
      - 
  nomgo1:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: